# Generated by Django 3.2.5 on 2021-11-07 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0003_auto_20211107_1328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='vehicle_no',
            field=models.IntegerField(max_length=100),
        ),
    ]
