# Generated by Django 3.2.5 on 2021-11-07 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0005_alter_booking_parking_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='exit',
            field=models.DateTimeField(),
        ),
    ]
